version: 2
jobs:
  install-venv:
    docker:
      - image: python:3.6.1
    working_directory: ~/place
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}
      - run:
          name: Make venv and install deps
          command: |
            python3 -m venv ~/place_venv
            . ~/place_venv/bin/activate
            pip install -r requirements.txt -r requirements_dev.txt --upgrade
      - save_cache:
          key: deps-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}
          paths:
            - "~/place_venv"
  test:
    docker:
      - image: python:3.6.1
    working_directory: ~/place
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}
      - run:
          name: Run tests
          command: |
            . ~/place_venv/bin/activate
            make test
  lint:
    docker:
      - image: python:3.6.1
    working_directory: ~/place
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}
      - run:
          name: Run lint
          command: |
            . ~/place_venv/bin/activate
            make lint
workflows:
  version: 2
  test-and-lint:
    jobs:
      - install-venv:
        filters:
          branches:
            ignore: master
      - lint:
        filters:
          branches:
            ignore: master
        requires:
          - install-venv
      - test:
        filters:
          branches:
            ignore: master
        requires:
          - lint
